var cities = {
    "Africa":["Cape Town","Marrakesh","Cairo","Pretoria","Durban",
                "Tenerife","Johannesburg","Lagos", "Stellenbosch"],
    "Arabia":["Riyadh","Jerusalem","Dubai","Jeddah","Mecca","Medina","Al Khobar","Dammam"],
    "Australia and The Pacific":["South Island","Tasmania","Sydney","Bora Bors",
                                "Fiji","Solomon Islands","Cook Islands"],
    "Carribean and Mexico":["Holbox","Cancun","Isla Mujeres","British Virgin Islands","Riviera Maya",
                            "Mexico City","Barbados","Saint Lucia",],
    "Asia":["Osaka","Bangkok","Shanghai","Singapore","Bali","Tokyo","Mumbai","Goa","Sri Lanka","Bali","Beijing",
            "Ho Chi Minh","Chennai","Kochi","New Delhi","Kuala Lumpur","Singapore"],
    "Europe":["Rome","Amsterdam","Paris","Barcelona","Venice","Frankfurt","Berlin","Budapest","Glasgow","Prague","Florence","Edinburgh",
            "Lisnon","Athens","Vienna","Madrid","Dublin","Malta","Copenhagen","Oslo","Munich","Stockholm","Porto","Luxembourg","Manchester"],
    "Central and South America":["San Salvador","Rio de Janeiro","Managua","Jaco","Granada","Quepos","Limon","Tamarindo","Monteverde","Antigua","San Jose","Panama City",
                                "Belize City","Jaco","Buenos Aires","Santiago","Mendoza","Aruba"],
    "North America":["New York","Atlanta","Toronto","Orlando","Las Vagas", "Los Angeles", "San Francisco", "Chicago", "Washington", "Miami", "Boston", "Seattle", "Vancouver","New Orleans",
                    "Philadelphia", "Denver", "Portland", "Montreal", "Honolulu", "San Antonio", "Cayman Island"],
}